version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_NAME=db_super
      - DB_USER=db_user
      - DB_PASS=pass

    command:
      - sh
      - -c
      - |
        sleep 3 &&
        cd /app/mydjango &&
        python manage.py migrate &&
        cd /app/myscrapy &&
        scrapy crawl spiderman &&
        cd /app/mydjango &&
        python manage.py runserver 0.0.0.0:8080


    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=db_super
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass
